RayCourse.Web/Areas/Dashboard/Models/Articles/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RayCourse.Web.Areas.Dashboard.Models.Articles
{
    public class CreateViewModel
    {
        [Required(
            ErrorMessageResourceName = "TitleRequired",
            ErrorMessageResourceType = typeof(Resources.Validation)
            )]
        [Display(
            Name = "Title",
            ResourceType = typeof(Resources.Fields)
            )]
        public string Title { get; set; }

        [Required(
            ErrorMessageResourceName = "ContentRequired",
            ErrorMessageResourceType = typeof(Resources.Validation)
            )]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        [Display(
            Name = "Content",
            ResourceType = typeof(Resources.Fields)
        )]
        public string Content { get; set; }

        [Required(
            ErrorMessageResourceName = "CourseRequired",
            ErrorMessageResourceType = typeof(Resources.Validation)
            )]
        [Display(
            Name = "Course",
            ResourceType = typeof(Resources.Common)
        )]
        public int Course { get; set; }

        public IEnumerable<SelectListItem> Courses { get; set; }
    }
}

RayCourse.Web/Areas/Dashboard/Controllers/ArticlesController.cs
using RayCourse.Data;
using RayCourse.Models;
using RayCourse.Web.Areas.Dashboard.Models.Articles;
using RayCourse.Web.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RayCourse.Web.Areas.Dashboard.Controllers
{
    [RouteArea("Dashboard")]
    [Authorize]
    public class ArticlesController : Controller
    {
        private const int pageSize = 10;

        private IAppContext db;
        private IAuthService auth;

        public ArticlesController()
        {
            this.db = new AppContext();
            this.auth = new AuthService(this.db);
        }

        public ArticlesController(IAppContext db, IAuthService auth)
        {
            this.db = db;
            this.auth = auth;
        }

        [HttpGet]
        public ActionResult Index(int page = 1, string sortBy = "")
        {
            var userId = this.auth.GetCurrentUserId();
            var articles = this.db.All<Article>().Include("Course").Where(x => x.Course.OwnerId == userId);
            switch (sortBy.ToLower())
            {
                case "course":
                    articles = articles.OrderBy(x => x.Course.Name);
                    break;
                case "title":
                    articles = articles.OrderBy(x => x.Title);
                    break;
                default:
                    articles = articles.OrderByDescending(x => x.CreatedOn);
                    break;
            }
            articles = articles.Skip((page - 1) * pageSize).Take(pageSize);

            var viewModel = new IndexViewModel
            {
                Articles = articles.Select(x => new IndexViewModel.Article
                {
                    Course = x.Course.Name,
                    CourseId = x.Course.Id,
                    CreatedOn = x.CreatedOn,
                    Id = x.Id,
                    Title = x.Title
                }).ToList(),
                Page = page,
                PageCount = this.db.Count<Article>(x => x.Course.OwnerId == userId) / 10 + 1,
                SortBy = sortBy
            };

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return this.redirectToIndex();
            }
            var article = this.db.Find<Article>(x => x.Id == id, "Course");
            if (article == null)
            {
                return HttpNotFound();
            }
            if (article.Course.OwnerId != this.auth.GetCurrentUserId())
            {
                return new HttpUnauthorizedResult();
            }

            var viewModel = new DetailsViewModel
            {
                Content = article.Content,
                CourseId = article.Course.Id,
                Id = article.Id,
                Title = article.Title,
                CreatedOn = article.CreatedOn,
                UpdatedOn = article.UpdatedOn
            };

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var userId = this.auth.GetCurrentUserId();
            var viewModel = new CreateViewModel
            {
                Courses = this.db.All<Course>().Where(x => x.OwnerId == userId).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title, Content, Course")]CreateViewModel viewModel)
        {
            var userId = this.auth.GetCurrentUserId();
            if (!ModelState.IsValid)
            {
                viewModel.Courses = this.db.All<Course>().Where(x => x.OwnerId == userId).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
                return View(viewModel);
            }

            var article = new Article
            {
                Content = viewModel.Content,
                CourseId = viewModel.Course,
                CreatedOn = DateTime.Now,
                UpdatedOn = DateTime.Now,
                Title = viewModel.Title
            };

            foreach (var user in this.db.Find<Course>(x => x.Id == viewModel.Course).FavouriteOf)
            {
                this.db.Add<Notification>(new Notification
                {
                    Parameter1 = this.auth.GetCurrentUser().Nickname,
                    Parameter2 = article.Title,
                    Type = NotificationType.ArticleAdded,
                    RecipientId = user.Id
                });
            }
            this.db.Add<Article>(article);
            this.db.SaveChanges();

            return this.redirectToIndex();
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var userId = this.auth.GetCurrentUserId();
            if (id == null)
            {
                return this.redirectToIndex();
            }
            var article = this.db.Find<Article>(x => x.Id == id, "Course");
            if (article == null)
            {
                return HttpNotFound();
            }
            if (article.Course.OwnerId != userId)
            {
                return new HttpUnauthorizedResult();
            }

            var viewModel = new EditViewModel
            {
                Content = article.Content,
                Course = article.Course.Id,
                Courses = this.db.All<Course>().Where(x => x.OwnerId == userId).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                Id = article.Id,
                Title = article.Title
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Title, Content, Course")]EditViewModel viewModel)
        {
            var userId = this.auth.GetCurrentUserId();
            if (!ModelState.IsValid)
            {
                viewModel.Courses = this.db.All<Course>().Where(x => x.OwnerId == userId).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
                return View(viewModel);
            }
            var article = this.db.Find<Article>(x => x.Id == viewModel.Id, "Course");
            if (article == null)
            {
                return HttpNotFound();
            }
            if (article.Course.OwnerId != userId)
            {
                return new HttpUnauthorizedResult();
            }

            article.Content = viewModel.Content;
            article.CourseId = viewModel.Course;
            article.Title = viewModel.Title;
            article.UpdatedOn = DateTime.Now;

            this.db.Update<Article>(article);
            this.db.SaveChanges();

            return this.redirectToIndex();
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var userId = this.auth.GetCurrentUserId();
            if (id == null)
            {
                return this.redirectToIndex();
            }
            var article = this.db.Find<Article>(x => x.Id == id, "Course");
            if (article == null)
            {
                return HttpNotFound();
            }
            if (article.Course.OwnerId != userId)
            {
                return new HttpUnauthorizedResult();
            }

            this.db.Delete<Article>(article);
            this.db.SaveChanges();

            return this.redirectToIndex();
        }

        private ActionResult redirectToIndex()
        {
            return Redirect("/dashboard/articles");
        }
    }
}

RayCourse.Web/Controllers/CoursesController.cs
using RayCourse.Data;
using RayCourse.Models;
using RayCourse.Web.Services;
using RayCourse.Web.Models.Courses;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RayCourse.Web.Controllers
{
    public class CoursesController : Controller
    {
        private IAppContext db;
        private IAuthService auth;
        private ICourseService courseService;

        private const int pageSize = 6;

        public CoursesController()
        {
            this.db = new AppContext();
            this.auth = new AuthService(db);
            this.courseService = new CourseService();
        }

        public CoursesController(IAppContext db, IAuthService auth, ICourseService courseService)
        {
            this.db = db;
            this.auth = auth;
            this.courseService = courseService;
        }

        [ChildActionOnly]
        public ActionResult MostFavourite()
        {
            var courses = this.db.All<Course>().Where(x => x.Type != CourseType.Hidden).Include(x => x.Owner).OrderByDescending(x => x.FavouriteOf.Count).ThenBy(x => x.Name).Take(5);
            var viewModel = courses.Select(x => new MostFavouriteViewModel
            {
                Name = x.Name,
                Owner = x.Owner.Nickname,
                Id = x.Id
            });
            return PartialView(viewModel);
        }


        [HttpGet]
        [Route("course/{id:int}")]
        public ActionResult Show(int id)
        {
            var course = this.db.Find<Course>(x => x.Id == id, "Owner");
            if (course == null)
            {
                return Redirect("/");
            }
            if (course.Type == CourseType.Private && !courseService.IsSetCookie(Request, course))
            {
                return Redirect("/course/" + course.Id + "/activate");
            }
            var viewModel = new ShowViewModel
            {
                Owner = course.Owner.Nickname,
                OwnerId = course.Owner.Id,
                Id = course.Id,
                Name = course.Name,
                IsFavourite = false,
                Description = course.Description,
                IsOwner = course.Owner.Id == this.auth.GetCurrentUserId(),
            };
            if (this.auth.IsLogged() && this.auth.GetCurrentUser().FavouriteCourses.Contains(course))
            {
                viewModel.IsFavourite = true;
            }
            return View(viewModel);
        }

        [HttpGet]
        [Route("course/{id:int}/activate")]
        public ActionResult Activate(int id)
        {
            var course = this.db.Find<Course>(x => x.Id == id);
            if (course == null)
            {
                return Redirect("/");
            }
            var viewModel = new ActivateViewModel
            {
                CourseId = course.Id
            };
            return View(viewModel);
        }

        [HttpPost]
        [Route("course/{id:int}/activate")]
        [ValidateAntiForgeryToken]
        public ActionResult Activate(int id, [Bind(Include = "CourseId, Password")]ActivateViewModel viewModel)
        {
            var course = this.db.Find<Course>(x => x.Id == id);
            if (course == null)
            {
                return Redirect("/");
            }
            if (course.Password != viewModel.Password)
            {
                ModelState.AddModelError("", RayCourse.Resources.Validation.WrongPassword);
                return View(viewModel);
            }

            HttpCookie cookie = new HttpCookie("course-" + course.Id);

            cookie.Value = course.Password;
            cookie.Expires = DateTime.Now.AddDays(1);

            Response.Cookies.Add(cookie);

            return Redirect("/course/" + course.Id);
        }

        [HttpGet]
        [Route("course/{id:int}/add-to-favourites")]
        [Authorize]
        public ActionResult AddToFavourites(int id)
        {
            var course = this.db.Find<Course>(x => x.Id == id);
            if (course == null)
            {
                return Redirect("/");
            }

            var user = this.auth.GetCurrentUser();

            if (user.Id == course.OwnerId)
            {
                return Redirect("/course/" + course.Id);
            }

            user.FavouriteCourses.Add(course);

            this.db.Add<Notification>(new Notification
            {
                Parameter1 = user.Nickname,
                Parameter2 = course.Name,
                Type = NotificationType.AddedToFavourites,
                RecipientId = course.OwnerId
            });
            this.db.Update<User>(user);
            this.db.SaveChanges();

            return Redirect("/course/" + course.Id);
        }

        [HttpGet]
        [Route("course/{id:int}/remove-from-favourites")]
        [Authorize]
        public ActionResult RemoveFromFavourites(int id)
        {
            var course = this.db.Find<Course>(x => x.Id == id);
            if (course == null)
            {
                return Redirect("/");
            }

            var user = this.auth.GetCurrentUser();

            if (user.Id == course.OwnerId)
            {
                return Redirect("/course/" + course.Id);
            }

            if (!user.FavouriteCourses.Contains(course))
            {
                return Redirect("/course/" + course.Id);
            }

            user.FavouriteCourses.Remove(course);
            this.db.Update<User>(user);
            this.db.SaveChanges();

            return Redirect("/course/" + course.Id);
        }

        [HttpGet]
        [Route("api/course/{id:int}/articles/{page:int}")]
        public ActionResult Articles(int id, int page)
        {
            var articles = this.db.All<Article>()
                .Where(x => x.CourseId == id)
                .OrderByDescending(x => x.CreatedOn)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            var viewModel = articles.Select(x => new ArticlesViewModel
            {
                Id = x.Id,
                Title = x.Title
            }).ToList();

            return Json(viewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("api/course/{id:int}/articles/page-count")]
        public ActionResult ArticlesPageCount(int id)
        {
            return Json(this.db.All<Article>().Where(x => x.CourseId == id).Count() / pageSize + 1, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("api/course/{id:int}/links/{page:int}")]
        public ActionResult Links(int id, int page)
        {
            var links = this.db.All<Link>()
                .Where(x => x.CourseId == id)
                .OrderByDescending(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            var viewModel = links.Select(x => new LinksViewModel
            {
                Id = x.Id,
                Title = x.Title,
                Url = x.Url
            }).ToList();

            return Json(viewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("api/course/{id:int}/links/page-count")]
        public ActionResult LinksPageCount(int id)
        {
            return Json(this.db.All<Link>().Where(x => x.CourseId == id).Count() / pageSize + 1, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("api/course/{id:int}/tests/{page:int}")]
        public ActionResult Tests(int id, int page)
        {
            var tests = this.db.All<Test>()
                .Where(x => x.CourseId == id)
                .OrderByDescending(x => x.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            var viewModel = tests.Select(x => new TestsViewModel
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();

            return Json(viewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("api/course/{id:int}/tests/page-count")]
        public ActionResult TestsPageCount(int id)
        {
            return Json(this.db.All<Test>().Where(x => x.CourseId == id).Count() / pageSize + 1, JsonRequestBehavior.AllowGet);
        }


    }
}

RayCourse.Web/Areas/Dashboard/Views/Articles/Create.cshtml
@model RayCourse.Web.Areas.Dashboard.Models.Articles.CreateViewModel

@{
    ViewBag.Title = RayCourse.Resources.Common.Create;
}

<h2>@RayCourse.Resources.Common.Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@RayCourse.Resources.Common.Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Course, Model.Courses, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@RayCourse.Resources.Common.Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/dashboard/articles">@RayCourse.Resources.Common.BackToList</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/tinymce/tinymce.min.js")
    @Scripts.Render("~/bundles/areas/dashboard/article")
}

RayCourse.Web/Areas/Dashboard/Views/Articles/Details.cshtml
@model RayCourse.Web.Areas.Dashboard.Models.Articles.DetailsViewModel

@{
    ViewBag.Title = RayCourse.Resources.Common.Details;
}

<h2>@RayCourse.Resources.Common.Create</h2>

<div class="row">
    <div class="col-md-6">
        <fieldset>
            <legend>@RayCourse.Resources.Common.Information</legend>
            <dl>
                <dt>@RayCourse.Resources.Fields.Title</dt>
                <dd>@Model.Title</dd>

                <dt>@RayCourse.Resources.Fields.CreatedOn</dt>
                <dd>@Model.CreatedOn</dd>

                <dt>@RayCourse.Resources.Fields.UpdatedOn</dt>
                <dd>@Model.UpdatedOn</dd>
            </dl>
        </fieldset>
    </div>
    <div class="col-md-6">
        <fieldset>
            <legend>@RayCourse.Resources.Common.Course</legend>
            @Html.Action("BriefDetails", "Courses", new { id = Model.CourseId })
        </fieldset>
    </div>
    <div class="col-md-12">
        <fieldset>
            <legend>@RayCourse.Resources.Fields.Content</legend>
            <div>
                @Html.Raw(Model.Content)
            </div>
        </fieldset>
    </div>
</div>
<div>
    <a href="/dashboard/articles/edit/@Model.Id">@RayCourse.Resources.Common.Edit</a> |
    <a href="/dashboard/articles">@RayCourse.Resources.Common.BackToList</a>
</div>

RayCourse.Web/Areas/Dashboard/Views/Articles/Edit.cshtml
@model RayCourse.Web.Areas.Dashboard.Models.Articles.EditViewModel

@{
    ViewBag.Title = RayCourse.Resources.Common.Edit;
}

<h2>@RayCourse.Resources.Common.Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@RayCourse.Resources.Common.Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Course, Model.Courses, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@RayCourse.Resources.Common.Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/dashboard/articles">@RayCourse.Resources.Common.BackToList</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/tinymce/tinymce.min.js")
    @Scripts.Render("~/bundles/areas/dashboard/article")
}

RayCourse.Web/Areas/Dashboard/Views/Articles/Index.cshtml
@model RayCourse.Web.Areas.Dashboard.Models.Articles.IndexViewModel

@{
    ViewBag.Title = "Index";
    ViewBag.Index = 1;
}

<h2>@RayCourse.Resources.Common.Articles</h2>

<div>
    <a href="/dashboard/articles/create">@RayCourse.Resources.Common.CreateNewArticle</a>
</div>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    <a href="/dashboard/articles?page=1&sortBy=title">@RayCourse.Resources.Fields.Title</a>
                </th>
                <th>
                    <a href="/dashboard/articles?page=1&sortBy=createdon">@RayCourse.Resources.Fields.CreatedOn</a>
                </th>
                <th>
                    <a href="/dashboard/articles?page=1&sortBy=course">@RayCourse.Resources.Common.Course</a>
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var article in Model.Articles)
            {
                <tr>
                    <td>
                        @(ViewBag.Index + (Model.Page - 1) * 10)
                    </td>
                    <td>
                        <a href="/dashboard/articles/details/@article.Id">@article.Title</a>
                    </td>
                    <td>
                        @article.CreatedOn
                    </td>
                    <td>
                        <a href="/dashboard/courses/details/@article.CourseId">@article.Course</a>
                    </td>
                    <td>
                        <a href="/dashboard/articles/details/@article.Id">@RayCourse.Resources.Common.Details</a> |
                        <a href="/dashboard/articles/edit/@article.Id">@RayCourse.Resources.Common.Edit</a> |
                        <a href="/dashboard/articles/delete/@article.Id">@RayCourse.Resources.Common.Delete</a>
                    </td>
                </tr>
                ViewBag.Index++;
            }
        </tbody>
    </table>
</div>
@Html.Partial("_Pager", new RayCourse.Web.Areas.Dashboard.Models.Shared.PagerViewModel
{
    Page = Model.Page,
    PageCount = Model.PageCount,
    BaseUrl = "/dashboard/articles",
    SortingEnabled = true,
    SortBy = Model.SortBy,
})